version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/smartthings_asus_router # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/node:12.8

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run:
          name: backend install
          command: npm i
      - run:
          name: ui install
          command: cd router-ui && npm i
      - run:
          name: backend lint
          command: npm run lint
      - run:
          name: ui lint
          command: cd router-ui && npm run lint
      - run:
          name:  ui build
          command: cd router-ui && npm run build:prod

