version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/smartthings_asus_router # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/node:12.8

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - add_ssh_keys:
          fingerprints:
            - "55:d4:38:8c:6f:4d:a9:d5:95:c0:0e:7a:d6:f1:ee:7e"
#      - run:
#          name: fix host authenticity for production server
#          command: ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts
      - run:
          name: create Keycloak.json
          command: echo $KEYCLOAK_JSON > keycloak.json
      - run:
          name: create branch name
          command: echo $CIRCLE_BRANCH > branch
      - run:
          name: backend install
          command: npm i
      - run:
          name: ui install
          command: cd router-ui && npm i
      - run:
          name: backend lint
          command: npm run lint
      - run:
          name: ui lint
          command: cd router-ui && npm run lint
      - run:
          name:  ui build
          command: cd router-ui && npm run build:dev
      - run:
          name: (HOME 1) clone master
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME@$SERVER_HOST -p $SERVER_PORT  'rm -rf /opt/app/asus && cd  /opt/app && git clone https://github.com/vzakharchenko/smartthings_asus_router asus'
      - run:
          name: (HOME 1) send branch name
          command:  scp -P $SERVER_PORT -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" branch $SERVER_USERNAME@$SERVER_HOST:/opt/app/asus/
      - run:
          name: (HOME 1) checkout branch
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME@$SERVER_HOST -p $SERVER_PORT  'cd /opt/app/asus && git checkout `cat branch`'
      - run:
          name: (HOME 1) send Keycloak.json
          command: scp  -P $SERVER_PORT -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" keycloak.json $SERVER_USERNAME@$SERVER_HOST:/opt/app/asus/config
      - run:
          name: (HOME 1) install backend
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME@$SERVER_HOST -p $SERVER_PORT  'cd  /opt/app/asus && npm i'
      - run:
          name: (HOME 1) send UI
          command:  scp -rp -P $SERVER_PORT -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ./router-ui/public $SERVER_USERNAME@$SERVER_HOST:/opt/app/asus/router-ui
      - run:
          name: (HOME 1) stop service
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME@$SERVER_HOST -p $SERVER_PORT  'cd  /opt/app/asus && pm2 stop AsusSmartAppServer.js && pm2 delete AsusSmartAppServer.js'
      - run:
          name: (HOME 1) start service
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME@$SERVER_HOST -p $SERVER_PORT  'cd  /opt/app/asus && pm2 start AsusSmartAppServer.js  && pm2 save'
      - run:
          name: (HOME 2) clone master
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME2@$SERVER_HOST2 -p $SERVER_PORT2  'rm -rf /opt/app/asus && cd  /opt/app && git clone https://github.com/vzakharchenko/smartthings_asus_router asus'
      - run:
          name: (HOME 2) send branch name
          command:  scp -P $SERVER_PORT2 -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" branch $SERVER_USERNAME2@$SERVER_HOST2:/opt/app/asus/
      - run:
          name: (HOME 2) checkout branch
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME2@$SERVER_HOST2 -p $SERVER_PORT2  'cd /opt/app/asus && git checkout `cat branch`'
      - run:
          name: (HOME 2) send Keycloak.json
          command: scp  -P $SERVER_PORT2 -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" keycloak.json $SERVER_USERNAME2@$SERVER_HOST2:/opt/app/asus/config
      - run:
          name: (HOME 2) install backend
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME2@$SERVER_HOST2 -p $SERVER_PORT2  'cd  /opt/app/asus && npm i'
      - run:
          name: (HOME 2) send UI
          command:  scp -rp -P $SERVER_PORT2 -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ./router-ui/public $SERVER_USERNAME2@$SERVER_HOST2:/opt/app/asus/router-ui
      - run:
          name: (HOME 2) stop service
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME2@$SERVER_HOST2 -p $SERVER_PORT2  'cd  /opt/app/asus && pm2 stop AsusSmartAppServer.js && pm2 delete AsusSmartAppServer.js'
      - run:
          name: (HOME 2) start service
          command: ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $SERVER_USERNAME2@$SERVER_HOST2 -p $SERVER_PORT2  'cd  /opt/app/asus && pm2 start AsusSmartAppServer.js  && pm2 save'

